srping.application.name=AIRBNB APP
spring.datasource.url=jdbc:postgresql://localhost:5432/AirBnb
spring.datasource.username=postgres
spring.datasource.password=Vaibhav9834@.
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true